#!/bin/sh

mkfs.btrfs -f -L HOME /dev/mmcblk0p1
mkfs.vfat -F 32 -n EFI /dev/sda1
mkswap /dev/sda2
swapon /dev/sda2
mkfs.btrfs -f -L ROOT /dev/sda3

mount /dev/sda3 /mnt
btrfs sub cr /mnt/@
btrfs sub cr /mnt/@log
btrfs sub cr /mnt/@pkg

mkdir /mnt/home
mount /dev/mmcblk0p1 /mnt/home
btrfs sub cr /mnt/home/@home
btrfs sub cr /mnt/home/@snapshots
umount /mnt/home
umount /mnt


mount -o noatime,space_cache=v2,ssd,compress=lzo,subvol=@ /dev/sda3 /mnt
mkdir -p /mnt/{boot/efi,home/snapshots,var/log,var/cache/pacman/pkg}
mount -o noatime,space_cache=v2,ssd,compress=lzo,subvol=@log /dev/sda3 /mnt/var/log
mount -o noatime,space_cache=v2,ssd,compress=lzo,subvol=@pkg /dev/sda3 /mnt/var/cache/pacman/pkg/
mount -o noatime,space_cache=v2,ssd,compress=lzo,subvol=@home /dev/mmcblk0p1 /mnt/home/
mkdir /mnt/home/snapshots
mount -o noatime,space_cache=v2,ssd,compress=lzo,subvolid=5,subvol=@snapshots /dev/sda3 /mnt/home/snapshots
mount /dev/sda1 /mnt/boot/efi/

pacstrap /mnt base linux linux-firmware nano intel-ucode btrfs-progs linux-headers linux-lts linux-lts-headers networkmanager
genfstab -U /mnt >> /mnt/etc/fstab
arch-chroot /mnt
ln -sf /usr/share/zoneinfo/Europe/Athens /etc/localtime
hwclock --systohc
